POST https://nodecrud-j9hb.onrender.com/videos
Content-Type: application/json

{
    "title": "Video Node",
    "description": "Esse é o vídeo numero 01",
    "duration": 180
}

###

GET https://nodecrud-j9hb.onrender.com/videos

###

PUT https://nodecrud-j9hb.onrender.com/videos/c1a711c1-d89d-4cbb-8cd0-6add7c0851fb
Content-Type: application/json

{
    "title": "render",
    "description": "Esse é o vídeo numero 02 alterado",
    "duration": 200
}

###

DELETE https://nodecrud-j9hb.onrender.com/videos/c1a711c1-d89d-4cbb-8cd0-6add7c0851fb


